language: python
python: 2.7
sudo: false
env:
- TOXENV=py27
install:
- "./.travis-workarounds.sh"
- pip install -U tox twine wheel
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: CJWIRI51KvqZrkPf7At1li+bbAZ/pN3iWRUPy0JaKWAC8O8B+GljXQxiXisPyLL1pIikcfLYZScOsKEhE+Uon/beeL1TPimVU3ELr7GYzuIkl3eK7quFUOiJ7glEggA5UyGNmk6goMVgaBQEOwT3gwH2LYwd1uFRvQsgIPY+tks=
  on:
    tags: true
    all_branches: true
    repo: scrapinghub/shub
    condition: "$TOXENV == py27"
